### PR TITLE
Enable AnnualMetrics module to correctly parse an occupancy schedule.

### PR DESCRIPTION
**Pull request by abbaad**
Unless I'm missing something, the code to parse an occupancy schedule parameter has a couple typos. Without this correction, the default schedule is always generated.

I don't know how your toolchain works in terms of compiling '.py' files into user objects, so my diff is only to the source file.

### CODE REVIEW

**Comment by chriswmackey** [comment]
Hi @abbaad ,
I'm not sure what you think is broken here. Are you using an hourly data collection for the occupancy schedule as the component input description says?

**Comment by abbaad** [comment]
I have tried to connect it to `schedule` output of the ConstantSchedule user object. I believe this is an instance of the class `ruleset.ScheduleRuleset`.

**Comment by chriswmackey** [comment]
Sorry for the incredibly late response but I see what you mean, @abbaad .  You were thinking that this component took a different type of object than what I was intending.  I was expecting a Ladybug data collection while you want to use the HB-Energy schedule object.  I think we can support HB-Energy schedules but let me make the change correctly, including updating the docstring to make it clear what is acceptable.

**Comment by chriswmackey** [comment]
I'm adding support for these changes as part of this PR:
https://github.com/ladybug-tools/honeybee-grasshopper-radiance/pull/65

So I am closing out this one here.

**Pull request closed without merging**
